[package]
name = "parrot"
version = "0.1.0"
authors = ["lightclient@protonmail.com <lightclient@protonmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
teloxide-core = "0.3"
tokio = { version =  "1.3", features = ["rt-multi-thread", "macros"] }
